/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.guessthelogo;
import java.awt.Color;
import static java.awt.Color.gray;
import static java.awt.Color.green;
import static java.awt.Color.orange;
import static java.awt.Color.red;
import static java.awt.Color.yellow;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.Random;
import javax.swing.*;
/**
 *
 * @author mac
 */
public final class gameWindow extends javax.swing.JFrame {

        int gameCount = 1;
        boolean gameOver = false;
        boolean reset = false;

        String input;

        String output = "Name:\tScore:\tDifficulty:";

        


        String [][] answers = new String [10][2];
        boolean usedLogos[] = new boolean[10];
        Random rand = new Random();   
        int j = rand.nextInt(10);


        String answerCorrect = "";
        int correct = 0;



    /**
     * Creates new form gameWindow
     */
    public gameWindow() {

        initComponents();
        options();
        setIcon();

        scoreBoardTextArea.setText(output);   
        nextLogo.setEnabled(false); 
        restartButton.setEnabled(false);
        companySelectionComboBox.setMaximumRowCount(3);  
        scoreSubmit.setEnabled(false);
        

    }

    public void options()   {

        answers[0][0] = "Adobe.jpg";        answers[0][1] = "Adobe";
        answers[1][0] = "Bic.jpg";          answers[1][1] = "Bic";
        answers[2][0] = "BP.jpg";           answers[2][1] = "BP";
        answers[3][0] = "Dominos.jpg";      answers[3][1] = "Dominos";
        answers[4][0] = "Linux.jpg";        answers[4][1] = "Linux";
        answers[5][0] = "Lufthansa.jpg";    answers[5][1] = "Lufthansa";
        answers[6][0] = "Mitsubishi.jpg";   answers[6][1] = "Mitsubishi";
        answers[7][0] = "Motorola.jpg";    answers[7][1] = "Motorola";
        answers[8][0] = "Rolex.jpg";        answers[8][1] = "Rolex";
        answers[9][0] = "Suzuki.jpg";       answers[9][1] = "Suzuki";

     }
    




    public void nextImage(){   

       do { 
           j = rand.nextInt(10);

           } while (usedLogos[j] == true);

   }  
 
 
    public void setIcon(){

       logoWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/".concat(answers[j][0]))));
       usedLogos[j] = true; 
       System.out.println(j);   

   }

    public void setNewIcon(){

       logoWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/".concat(answers[j][0]))));
       System.out.println(j); 

   } 
 
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        gamePanel = new javax.swing.JPanel();
        nextLogo = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        feedbackTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        companySelectionComboBox = new javax.swing.JComboBox<>();
        selectCompanyLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logoWindow = new javax.swing.JLabel();
        controlPanel = new javax.swing.JPanel();
        difficultyPanel = new javax.swing.JPanel();
        difficultyLabel = new javax.swing.JLabel();
        easyRadioButton = new javax.swing.JRadioButton();
        mediumRadioButton = new javax.swing.JRadioButton();
        hardRadioButton = new javax.swing.JRadioButton();
        controlPanelLabel = new javax.swing.JLabel();
        restartButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoreBoardTextArea = new javax.swing.JTextArea();
        scoreBoardPanelLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        scoreSubmit = new javax.swing.JButton();
        nameInput = new javax.swing.JTextField();
        nameInputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guess The Logo");
        setBackground(new java.awt.Color(99, 46, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));

        gamePanel.setBackground(new java.awt.Color(255, 153, 153));
        gamePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nextLogo.setBackground(java.awt.Color.lightGray);
        nextLogo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        nextLogo.setForeground(new java.awt.Color(255, 0, 255));
        nextLogo.setText("Next Logo");
        nextLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextLogoActionPerformed(evt);
            }
        });
        nextLogo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nextLogoKeyReleased(evt);
            }
        });

        submitButton.setBackground(java.awt.Color.lightGray);
        submitButton.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 0, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        submitButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submitButtonKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                submitButtonKeyReleased(evt);
            }
        });

        feedbackTextField.setEditable(false);
        feedbackTextField.setBackground(java.awt.Color.gray);
        feedbackTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        feedbackTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        feedbackTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(102, 64, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        companySelectionComboBox.setBackground(new java.awt.Color(255, 179, 223));
        companySelectionComboBox.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        companySelectionComboBox.setForeground(new java.awt.Color(255, 51, 51));
        companySelectionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adobe", "Bic", "BP", "Dominos", "Linux", "Lufthansa", "Mitsubishi", "Motorola", "Rolex", "Suzuki" }));
        companySelectionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companySelectionComboBoxActionPerformed(evt);
            }
        });

        selectCompanyLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        selectCompanyLabel.setForeground(new java.awt.Color(255, 153, 153));
        selectCompanyLabel.setText("Select Company");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(companySelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(selectCompanyLabel)
                        .addGap(43, 43, 43))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectCompanyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(companySelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel3.setBackground(new java.awt.Color(238, 238, 59));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(171, 119, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(356, 277));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(logoWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nextLogo)
                .addGap(118, 118, 118)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
            .addComponent(feedbackTextField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(gamePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feedbackTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        controlPanel.setBackground(new java.awt.Color(238, 171, 17));
        controlPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        difficultyPanel.setBackground(new java.awt.Color(153, 153, 153));
        difficultyPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        difficultyLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        difficultyLabel.setText("Choose Game Difficulty");

        buttonGroup1.add(easyRadioButton);
        easyRadioButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        easyRadioButton.setForeground(new java.awt.Color(51, 255, 51));
        easyRadioButton.setSelected(true);
        easyRadioButton.setText("Easy");
        easyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(mediumRadioButton);
        mediumRadioButton.setFont(new java.awt.Font("Chalkboard SE", 0, 18)); // NOI18N
        mediumRadioButton.setForeground(new java.awt.Color(255, 255, 145));
        mediumRadioButton.setText("Medium");
        mediumRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(hardRadioButton);
        hardRadioButton.setFont(new java.awt.Font("Chalkduster", 1, 18)); // NOI18N
        hardRadioButton.setForeground(new java.awt.Color(240, 0, 51));
        hardRadioButton.setText("Hard");
        hardRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout difficultyPanelLayout = new javax.swing.GroupLayout(difficultyPanel);
        difficultyPanel.setLayout(difficultyPanelLayout);
        difficultyPanelLayout.setHorizontalGroup(
            difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(difficultyPanelLayout.createSequentialGroup()
                .addGroup(difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(difficultyPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(easyRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mediumRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hardRadioButton))
                    .addGroup(difficultyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(difficultyLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        difficultyPanelLayout.setVerticalGroup(
            difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(difficultyPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(difficultyLabel)
                .addGap(38, 38, 38)
                .addGroup(difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mediumRadioButton)
                    .addComponent(hardRadioButton)
                    .addComponent(easyRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        controlPanelLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        controlPanelLabel.setText("Control Panel");

        restartButton.setBackground(new java.awt.Color(0, 0, 0));
        restartButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        restartButton.setForeground(new java.awt.Color(255, 0, 0));
        restartButton.setText("Restart");
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(difficultyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(controlPanelLabel))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controlPanelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(difficultyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(restartButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(238, 216, 185));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        scoreBoardTextArea.setEditable(false);
        scoreBoardTextArea.setColumns(12);
        scoreBoardTextArea.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        scoreBoardTextArea.setRows(5);
        scoreBoardTextArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(scoreBoardTextArea);

        scoreBoardPanelLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        scoreBoardPanelLabel.setText("Score Board");

        jPanel2.setBackground(new java.awt.Color(238, 194, 238));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        scoreSubmit.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        scoreSubmit.setForeground(new java.awt.Color(255, 0, 102));
        scoreSubmit.setText("Submit");
        scoreSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreSubmitActionPerformed(evt);
            }
        });

        nameInput.setEditable(false);
        nameInput.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nameInput.setBorder(null);
        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });

        nameInputLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nameInputLabel.setText("Name:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(nameInputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(scoreSubmit)
                        .addGap(66, 66, 66))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameInputLabel))
                .addGap(18, 18, 18)
                .addComponent(scoreSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(scoreBoardPanelLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scoreBoardPanelLabel)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gamePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextLogoActionPerformed
      
        nextImage();    
        setNewIcon();   
        submitButton.setEnabled(true);  
        nextLogo.setEnabled(false);    
        feedbackTextField. setText("");
        companySelectionComboBox.setSelectedIndex (0); 
        feedbackTextField.setBackground(gray);
        usedLogos[j] = true;  
        
    
    }//GEN-LAST:event_nextLogoActionPerformed

    private void companySelectionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companySelectionComboBoxActionPerformed
     
    }//GEN-LAST:event_companySelectionComboBoxActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        easyRadioButton.setEnabled(false);
        mediumRadioButton.setEnabled(false);
        hardRadioButton.setEnabled(false); 

        nameInput.setEditable(true);
        scoreSubmit.setEnabled(true);


        submitButton.setEnabled(false); 
        

        String answerBox, answerPic;

        answerBox = companySelectionComboBox.getSelectedItem().toString();
        answerPic = answers[j][1];
        System.out.println(answerBox);

      if (answerPic.equals(answerBox))
       {
        nextLogo.setEnabled(true); 
        feedbackTextField.setText("Correct!!");
        feedbackTextField.setBackground(green);
        correct++;
       }
        else
       {
        nextLogo.setEnabled(true); 
        feedbackTextField. setText("Inorrect!! The correct answer is " + answerPic);
        feedbackTextField.setBackground(red);
       }

      if(gameCount == 5 && easyRadioButton.isSelected())
       {
        
        logoWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/GameOver.png")));   
        feedbackTextField.setBackground(green);
        feedbackTextField. setText("Congratulations your score is " + correct + "/5");
        nextLogo.setEnabled(false); 
        logoWindow.setSize(255,255);
        companySelectionComboBox.addItem("Game Over");
        companySelectionComboBox.setSelectedIndex (10); 
        companySelectionComboBox.setEnabled (false); 
        JOptionPane.showMessageDialog(null, "Enter Your Name To Be Added To The Score Board", "Well Done!!!", JOptionPane.INFORMATION_MESSAGE);
        answerCorrect= correct + "/5\t Easy";
        gameOver = true;
        

       }

       
      if(gameCount == 7 && mediumRadioButton.isSelected())
        {
            
        feedbackTextField.setBackground(green);
        feedbackTextField. setText("Congratulations your score is " + correct + "/7");
        logoWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/GameOver.png")));  
        nextLogo.setEnabled(false); 
        logoWindow.setSize(255,255);
        companySelectionComboBox.addItem("Game Over");
        companySelectionComboBox.setSelectedIndex (10); 
        companySelectionComboBox.setEnabled (false); 
        JOptionPane.showMessageDialog(null, "Enter Your Name To Be Added To The Score Board", "Well Done!!!", JOptionPane.INFORMATION_MESSAGE);
        answerCorrect= correct + "/7\t Medium";
        gameOver = true;

        }
       
    if(gameCount == 10 && hardRadioButton.isSelected())
        {

        feedbackTextField.setBackground(green);
        feedbackTextField. setText("Congratulations your score is " + correct + "/10");
        logoWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/GameOver.png")));  
        nextLogo.setEnabled(false); 
        logoWindow.setSize(255,255);
        companySelectionComboBox.addItem("Game Over");
        companySelectionComboBox.setSelectedIndex (10); 
        companySelectionComboBox.setEnabled (false); 
        JOptionPane.showMessageDialog(null, "Enter Your Name To Be Added To The Score Board", "Well Done!!!", JOptionPane.INFORMATION_MESSAGE);
        answerCorrect= correct + "/10\t Hard";
        gameOver = true;

        }
       
       
        gameCount++;
     
    }//GEN-LAST:event_submitButtonActionPerformed

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        System.out.println("New Game");  

        usedLogos = new boolean[10];  
        rand = new Random(); 
        j = rand.nextInt(10); 


        setIcon();         

        gameCount = 1;
        gameOver = false;
        correct = 0;
        submitButton.setEnabled(true);    
        feedbackTextField. setText("");
        companySelectionComboBox.removeItem("Game Over");
        companySelectionComboBox.setSelectedIndex (0);   
        feedbackTextField.setBackground(gray);
        restartButton.setEnabled(false);
        logoWindow.setSize(255,255);  
        easyRadioButton.setEnabled(true);
        mediumRadioButton.setEnabled(true);
        easyRadioButton.setSelected(true);
        hardRadioButton.setEnabled(true);
        companySelectionComboBox.setEnabled (true); 

    }//GEN-LAST:event_restartButtonActionPerformed

    private void hardRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardRadioButtonActionPerformed
        System.out.println("New Game");  
        logoWindow.setSize(100,100);
       
       usedLogos = new boolean[10];  
       rand = new Random(); 
       j = rand.nextInt(10); 

        setIcon(); 

    }//GEN-LAST:event_hardRadioButtonActionPerformed

    private void easyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyRadioButtonActionPerformed
        System.out.println("New Game");  
        logoWindow.setSize(255,255);
       usedLogos = new boolean[10];  
       rand = new Random(); 
       j = rand.nextInt(10); 

       setIcon(); 

    }//GEN-LAST:event_easyRadioButtonActionPerformed

    private void mediumRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumRadioButtonActionPerformed
         System.out.println("New Game");  
        logoWindow.setSize(100,255); 
       
        usedLogos = new boolean[10];  
        rand = new Random(); 
        j = rand.nextInt(10); 

        setIcon(); 
        
    }//GEN-LAST:event_mediumRadioButtonActionPerformed

    private void submitButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submitButtonKeyPressed

        
        
    }//GEN-LAST:event_submitButtonKeyPressed

    private void submitButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submitButtonKeyReleased

                // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonKeyReleased

    private void nextLogoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nextLogoKeyReleased
 
    }//GEN-LAST:event_nextLogoKeyReleased

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameInputActionPerformed

    private void scoreSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreSubmitActionPerformed
    
        input = nameInput.getText();
        output +=  "\n" + input + "\t" + answerCorrect; 
        scoreBoardTextArea.setText(output);
        nameInput.setText(" ");
        scoreSubmit.setEnabled(false);
        nameInput.setEditable(false);
        restartButton.setEnabled(true);
        JOptionPane.showMessageDialog(this, "Click Restart to try again", "Want to play again?", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_scoreSubmitActionPerformed



    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> companySelectionComboBox;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel controlPanelLabel;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JPanel difficultyPanel;
    private javax.swing.JRadioButton easyRadioButton;
    private javax.swing.JTextField feedbackTextField;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JRadioButton hardRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoWindow;
    private javax.swing.JRadioButton mediumRadioButton;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameInputLabel;
    private javax.swing.JButton nextLogo;
    private javax.swing.JButton restartButton;
    private javax.swing.JLabel scoreBoardPanelLabel;
    private javax.swing.JTextArea scoreBoardTextArea;
    private javax.swing.JButton scoreSubmit;
    private javax.swing.JLabel selectCompanyLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
